ALTER TABLE sigmets ADD COLUMN IF NOT EXISTS scope VARCHAR(20) DEFAULT 'DOMESTIC';
ALTER TABLE sigmets ADD COLUMN IF NOT EXISTS fir_id VARCHAR(10);
ALTER TABLE sigmets ADD COLUMN IF NOT EXISTS fir_name VARCHAR(100);

CREATE INDEX IF NOT EXISTS idx_sigmet_scope ON sigmets(scope);
