-- Create weather_forecasts table for storing public weather forecast data
CREATE TABLE weather_forecasts (
    id BIGSERIAL PRIMARY KEY,
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    source VARCHAR(50) NOT NULL,

    -- Time information
    forecast_time TIMESTAMP NOT NULL,
    valid_from TIMESTAMP NOT NULL,
    valid_to TIMESTAMP NOT NULL,
    fetched_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Coordinates (denormalized for queries)
    latitude DECIMAL(10, 7) NOT NULL,
    longitude DECIMAL(10, 7) NOT NULL,

    -- Weather data (JSONB for flexibility)
    forecast_data JSONB NOT NULL,

    -- Extracted searchable fields
    temperature_fahrenheit DECIMAL(5, 2),
    temperature_celsius DECIMAL(5, 2),
    precipitation_probability INTEGER,
    wind_speed_mph DECIMAL(5, 2),
    wind_direction INTEGER,
    humidity INTEGER,
    weather_description TEXT,
    weather_short_description VARCHAR(255),

    -- Metadata
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_source CHECK (source IN ('noaa', 'openweathermap')),
    CONSTRAINT ck_precipitation_probability CHECK (precipitation_probability >= 0 AND precipitation_probability <= 100),
    CONSTRAINT ck_wind_direction CHECK (wind_direction >= 0 AND wind_direction <= 360),
    CONSTRAINT ck_humidity CHECK (humidity >= 0 AND humidity <= 100)
);

-- Create indexes for efficient querying
CREATE INDEX idx_forecast_location ON weather_forecasts(location_id);
CREATE INDEX idx_forecast_source ON weather_forecasts(source);
CREATE INDEX idx_forecast_valid_from ON weather_forecasts(valid_from);
CREATE INDEX idx_forecast_valid_to ON weather_forecasts(valid_to);
CREATE INDEX idx_forecast_fetched_at ON weather_forecasts(fetched_at);
CREATE INDEX idx_forecast_coordinates ON weather_forecasts(latitude, longitude);
CREATE INDEX idx_forecast_active ON weather_forecasts(is_active);
CREATE INDEX idx_forecast_data ON weather_forecasts USING GIN(forecast_data);

-- Composite indexes for common query patterns
CREATE INDEX idx_forecast_location_time ON weather_forecasts(location_id, valid_from, valid_to);
CREATE INDEX idx_forecast_location_active ON weather_forecasts(location_id, is_active) WHERE is_active = true;
CREATE INDEX idx_forecast_source_active ON weather_forecasts(source, is_active) WHERE is_active = true;
CREATE INDEX idx_forecast_time_range ON weather_forecasts(valid_from, valid_to, is_active) WHERE is_active = true;

-- Add comments to table
COMMENT ON TABLE weather_forecasts IS 'Public weather forecasts from NOAA and OpenWeatherMap';
COMMENT ON COLUMN weather_forecasts.source IS 'Data source: noaa or openweathermap';
COMMENT ON COLUMN weather_forecasts.forecast_time IS 'When the forecast was generated by the source';
COMMENT ON COLUMN weather_forecasts.valid_from IS 'Start of forecast validity period';
COMMENT ON COLUMN weather_forecasts.valid_to IS 'End of forecast validity period';
COMMENT ON COLUMN weather_forecasts.fetched_at IS 'When we fetched this data from the source';
COMMENT ON COLUMN weather_forecasts.forecast_data IS 'Full forecast data as JSON';
COMMENT ON COLUMN weather_forecasts.is_active IS 'Whether this forecast is still active (for soft deletes)';
