apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: weather-dashboard-event-listener
  namespace: weather-dashboard-dev
spec:
  serviceAccountName: pipeline-sa
  triggers:
    - name: github-push-trigger
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-webhook-secret
                secretKey: token
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.ref.startsWith('refs/heads/main')"
      bindings:
        - ref: weather-dashboard-trigger-binding
      template:
        ref: weather-dashboard-trigger-template
---
apiVersion: v1
kind: Service
metadata:
  name: el-weather-dashboard-event-listener
  namespace: weather-dashboard-dev
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    eventlistener: weather-dashboard-event-listener
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: weather-dashboard-webhook
  namespace: weather-dashboard-dev
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-weather-dashboard-event-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
